[package]
name = "hudhud-regex"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
regex = "1"
hudhudscript-bytecode = { path = "../hudhudscript-bytecode" }
hudhudscript-errors = { path = "../hudhudscript-errors" }
