use crate::catalog::{ErrorCategory, ErrorCode, ErrorEntry};

pub static ENTRIES: &[ErrorEntry] = &[
    GGUF_INVALID_MAGIC,
    GGUF_INVALID_UTF8,
    GGUF_TOO_SHORT,
    GGUF_UNEXPECTED_EOF,
    GGUF_UNSUPPORTED_VERSION,
    GRAPH_CIRCULAR_DEPENDENCY,
    GRAPH_MODULE_NOT_FOUND,
    HF_DESERIALIZE,
    HF_HTTP,
    MODEL_MANAGER_ALREADY_EXISTS,
    MODEL_MANAGER_INSUFFICIENT_DISK_SPACE,
    MODEL_MANAGER_IO,
    MODEL_MANAGER_NOT_FOUND,
    MODULE_LOADER_ALREADY_LOADED,
    MODULE_LOADER_MODULE_NOT_FOUND,
    MODULE_LOADER_PARSE_ERROR,
    MODULE_LOADER_READ_ERROR,
    OLLAMA_DESERIALIZE,
    OLLAMA_HTTP,
    PACKAGE_BUILD_FAILED,
    PACKAGE_CHECKSUM_MISMATCH,
    PACKAGE_DEPENDENCY_RESOLUTION,
    PACKAGE_ENTRY_POINT_NOT_FOUND,
    PACKAGE_INVALID_PACKAGE_NAME,
    PACKAGE_INVALID_VERSION,
    PACKAGE_IO,
    PACKAGE_NETWORK,
    PACKAGE_OTHER,
    PACKAGE_PACKAGE_NOT_FOUND,
    PACKAGE_SECURITY_VULNERABILITY,
    PACKAGE_SERIALIZATION,
    PACKAGE_TOML,
    PACKAGE_TOML_SERIALIZE,
    PACKAGE_VERSION_NOT_FOUND,
    RESOLVER_INVALID_PATH,
    RESOLVER_NOT_FOUND,
];

mod core;
mod deploy;
mod loader;
pub use core::*;
pub use deploy::*;
pub use loader::*;
