use crate::catalog::category::ExceptionCategory;
use crate::catalog::codes::ExceptionCode;
use crate::catalog::entry::ExceptionEntry;

mod community;
pub use community::*;
mod constitution;
pub use constitution::*;
mod council;
pub use council::*;
mod coup;
pub use coup::*;
mod governance;
pub use governance::*;
mod perspective;
pub use perspective::*;
mod role;
pub use role::*;
mod swarm;
pub use swarm::*;

pub static TABLE: &[ExceptionEntry] = &[
    COMMUNITY_COUNCIL_NOT_FOUND,
    COMMUNITY_DUPLICATE_COUNCIL,
    COMMUNITY_DUPLICATE_MEMBER,
    COMMUNITY_DUPLICATE_RESOURCE,
    COMMUNITY_INVALID_CONFIGURATION,
    COMMUNITY_MEMBER_NOT_FOUND,
    COMMUNITY_RESOURCE_NOT_FOUND,
    CONSTITUTION_INVALID_VERSION,
    CONSTITUTION_LAW_NOT_FOUND,
    CONSTITUTION_NO_PREVIOUS_VERSION,
    CONSTITUTION_NOT_FOUND,
    COUNCIL_AGENT_NOT_FOUND,
    COUNCIL_CONSTITUTION_NOT_FOUND,
    COUNCIL_DUPLICATE_AGENT,
    COUNCIL_EXECUTION_FAILED,
    COUNCIL_INVALID_ROLE,
    COUNCIL_NO_MEMBERS,
    COUNCIL_NOT_FOUND,
    COUNCIL_TIMEOUT,
    COUP_AGENT_NOT_FOUND,
    COUP_CONSTITUTION_NOT_FOUND,
    GOVERNANCE_AGENT_NOT_FOUND,
    GOVERNANCE_CACHE_ID_COLLISION,
    GOVERNANCE_CIRCULAR_DEPENDENCY,
    GOVERNANCE_CONSTITUTION_NOT_FOUND,
    GOVERNANCE_FORMAT_VALIDATION,
    GOVERNANCE_INVALID_CONFIGURATION,
    GOVERNANCE_INVALID_ROLE,
    GOVERNANCE_RESOURCE_NOT_FOUND,
    GOVERNANCE_SERIALIZATION_ERROR,
    PERSPECTIVE_FIELD_HIDDEN,
    PERSPECTIVE_WRITE_ACCESS_DENIED,
    ROLE_INVALID_ROLE,
    ROLE_PERMISSION_NOT_FOUND,
    ROLE_ROLE_NOT_FOUND,
    SWARM_AGENT_FAILED,
    SWARM_AGENT_NOT_FOUND,
    SWARM_DUPLICATE_AGENT,
    SWARM_INSUFFICIENT_SUCCESS,
    SWARM_NO_AGENTS,
    SWARM_STATE_KEY_NOT_FOUND,
    SWARM_TIMEOUT,
];
