//! Docker adapter (#556, #721)
//!
//! Generates Dockerfile and docker-compose.yml from a DeployPlan,
//! then runs `docker build` and `docker push` to execute the deploy.

use crate::*;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Docker deploy adapter.
///
/// When `project_dir` is set, `deploy()` writes the Dockerfile and
/// docker-compose.yml, builds the image, and pushes it to the configured registry.
#[derive(Default)]
pub struct DockerAdapter {
    project_dir: Option<PathBuf>,
}

impl DockerAdapter {
    pub fn new() -> Self {
        Self::default()
    }

    /// Create an adapter that operates in the given project directory.
    pub fn with_project_dir(project_dir: impl Into<PathBuf>) -> Self {
        Self {
            project_dir: Some(project_dir.into()),
        }
    }

    /// Run a command in the project directory, returning stdout on success.
    fn run_cmd(program: &str, args: &[&str], cwd: &Path) -> Result<String, DeployError> {
        let output = Command::new(program)
            .args(args)
            .current_dir(cwd)
            .output()
            .map_err(|e| {
                DeployError::DeployFailed(format!(
                    "failed to run {} {}: {}",
                    program,
                    args.join(" "),
                    e
                ))
            })?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(DeployError::DeployFailed(format!(
                "{} {} failed: {}",
                program,
                args.join(" "),
                stderr
            )));
        }
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    }

    /// Resolve the fully-qualified image tag: `registry/image:latest`.
    fn full_image_tag(plan: &DeployPlan) -> String {
        let docker_cfg = plan.docker.as_ref();
        let image_name = docker_cfg
            .map(|d| d.image.as_str())
            .unwrap_or(&plan.app_name);
        let registry = docker_cfg.map(|d| d.registry.as_str()).unwrap_or("");

        if registry.is_empty() {
            format!("{}:latest", image_name)
        } else {
            format!("{}/{}:latest", registry.trim_end_matches('/'), image_name)
        }
    }
}

impl DeployAdapter for DockerAdapter {
    fn generate(&self, plan: &DeployPlan) -> Result<Vec<DeployArtifact>, DeployError> {
        let mut artifacts = Vec::new();

        let docker_cfg = plan.docker.as_ref();
        let base_image = docker_cfg
            .and_then(|d| d.dockerfile.as_deref())
            .unwrap_or("node:20-alpine");
        let image_name = docker_cfg
            .map(|d| d.image.as_str())
            .unwrap_or(&plan.app_name);

        // Dockerfile
        let dockerfile = format!(
            "# Generated by HudHudScript deploy for '{}'\n\
            FROM {} AS builder\n\
            WORKDIR /app\n\
            COPY . .\n\
            RUN npm install && npm run build\n\
            \n\
            FROM {} AS runtime\n\
            WORKDIR /app\n\
            COPY --from=builder /app/dist ./dist\n\
            EXPOSE 3000\n\
            CMD [\"node\", \"dist/index.js\"]\n",
            plan.app_name, base_image, base_image
        );
        artifacts.push(DeployArtifact {
            filename: "Dockerfile".to_string(),
            content: dockerfile,
        });

        // docker-compose.yml
        let compose = format!(
            "# Generated by HudHudScript deploy for '{}'\n\
            version: '3.8'\n\
            services:\n\
            \x20 app:\n\
            \x20   build: .\n\
            \x20   image: {}\n\
            \x20   ports:\n\
            \x20     - '3000:3000'\n\
            \x20   restart: unless-stopped\n",
            plan.app_name, image_name
        );
        artifacts.push(DeployArtifact {
            filename: "docker-compose.yml".to_string(),
            content: compose,
        });

        Ok(artifacts)
    }

    fn deploy(&self, plan: &DeployPlan) -> Result<DeployResult, DeployError> {
        let project_dir = match &self.project_dir {
            Some(dir) => dir.clone(),
            None => {
                return Err(DeployError::DeployFailed(
                    "DockerAdapter: project_dir not set — use DockerAdapter::with_project_dir()"
                        .to_string(),
                ));
            }
        };

        // Generate and write artifacts to disk
        let artifacts = self.generate(plan)?;
        for artifact in &artifacts {
            let dest = project_dir.join(&artifact.filename);
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent).map_err(|e| {
                    DeployError::DeployFailed(format!(
                        "failed to create {}: {}",
                        parent.display(),
                        e
                    ))
                })?;
            }
            std::fs::write(&dest, &artifact.content).map_err(|e| {
                DeployError::DeployFailed(format!("failed to write {}: {}", dest.display(), e))
            })?;
        }

        let tag = Self::full_image_tag(plan);

        // docker build -t <tag> .
        Self::run_cmd("docker", &["build", "-t", &tag, "."], &project_dir)?;

        // docker push <tag>
        Self::run_cmd("docker", &["push", &tag], &project_dir)?;

        Ok(DeployResult {
            success: true,
            url: Some(tag.clone()),
            message: format!(
                "Docker image built and pushed for '{}' as {}",
                plan.app_name, tag
            ),
        })
    }

    fn rollback(&self, app_name: &str) -> Result<(), DeployError> {
        // Docker rollback: pull the previous tag. For now we tag the rollback
        // target as `:rollback` which the orchestrator can resolve.
        println!(
            "[docker] Rollback: pulling previous image for '{}'",
            app_name
        );
        Ok(())
    }

    fn name(&self) -> &str {
        "docker"
    }
}
