[package]
name = "hudhud-translate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
hudhudscript-bytecode = { path = "../hudhudscript-bytecode" }
hudhudscript-errors = { path = "../hudhudscript-errors" }
hudhud-http = { path = "../hudhud-http" }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
