use super::{ErrorCategory, ErrorCode, ErrorEntry};

pub static ENTRIES: &[ErrorEntry] = &[
    ASYNC_RUNTIME_PROMISE_NOT_FOUND,
    ASYNC_RUNTIME_RUNTIME_ERROR,
    ASYNC_RUNTIME_TASK_SPAWN_FAILED,
    RUNTIME_AGENT_ALREADY_EXISTS,
    RUNTIME_AGENT_NOT_FOUND,
    RUNTIME_BREAK,
    RUNTIME_CALL_ERROR,
    RUNTIME_CONTINUE,
    RUNTIME_CUSTOM,
    RUNTIME_DIVISION_BY_ZERO,
    RUNTIME_EXECUTION_FAILED,
    RUNTIME_GOVERNANCE_VIOLATION,
    RUNTIME_IMMUTABLE_VARIABLE,
    RUNTIME_INDEX_OUT_OF_BOUNDS,
    RUNTIME_INVALID_OPERATION,
    RUNTIME_MODULE_ERROR,
    RUNTIME_OUT_OF_GAS,
    RUNTIME_PROMISE_REJECTED,
    RUNTIME_PROPERTY_NOT_FOUND,
    RUNTIME_RESOURCE_ERROR,
    RUNTIME_RETURN,
    RUNTIME_SECURITY_VIOLATION,
    RUNTIME_STACK_OVERFLOW,
    RUNTIME_STATE_ERROR,
    RUNTIME_STM_MAX_RETRIES_EXCEEDED,
    RUNTIME_STM_TIMEOUT,
    RUNTIME_TASK_NOT_FOUND,
    RUNTIME_THROW,
    RUNTIME_TOOL_ERROR,
    RUNTIME_TYPE_ERROR,
    RUNTIME_UNDEFINED_VARIABLE,
    RUNTIME_UNINITIALIZED_VARIABLE,
    RUNTIME_VARIABLE_ALREADY_DEFINED,
    RUNTIME_YIELD,
];

mod core;
mod tasks;
pub use core::*;
pub use tasks::*;
