use crate::catalog::{ErrorCategory, ErrorCode, ErrorEntry};

pub static ENTRIES: &[ErrorEntry] = &[
    COST_BUDGET_EXCEEDED,
    COST_UNKNOWN_MODEL,
    COST_UNKNOWN_PROVIDER,
    RATE_LIMIT_RPM_EXCEEDED,
    RATE_LIMIT_TPM_EXCEEDED,
    TOKENOMICS_BUDGET_NOT_FOUND,
    TOKENOMICS_CACHE_ERROR,
    TOKENOMICS_COLD_START,
    TOKENOMICS_CONFIG_ERROR,
    TOKENOMICS_DATABASE_ERROR,
    TOKENOMICS_FEDERATED_ERROR,
    TOKENOMICS_INSUFFICIENT_BUDGET,
    TOKENOMICS_INVALID_BUDGET,
    TOKENOMICS_IO_ERROR,
    TOKENOMICS_MODEL_DRIFT,
    TOKENOMICS_MODEL_ERROR,
    TOKENOMICS_OVERFITTING,
    TOKENOMICS_PREDICTION_FAILED,
    TOKENOMICS_REDIS_ERROR,
    TOKENOMICS_REINFORCEMENT_ERROR,
    TOKENOMICS_SERIALIZATION_ERROR,
    TOKENOMICS_STORAGE_ERROR,
    TOKENOMICS_UNKNOWN,
];

mod budget;
mod core;
pub use budget::*;
pub use core::*;
