[package]
name = "hudhudscript-mir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
hudhudscript-localization = { path = "../hudhudscript-localization" }
hudhudscript-types = { path = "../hudhudscript-types" }

[dev-dependencies]
hudhudscript-parser = { path = "../hudhudscript-parser" }
hudhudscript-types = { path = "../hudhudscript-types" }
