[package]
name = "hudhud-math"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rand = "0.8"
hudhudscript-bytecode = { path = "../hudhudscript-bytecode" }
hudhudscript-errors = { path = "../hudhudscript-errors" }
