[package]
name = "hudhud-web-response"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hudhudscript-bytecode = { path = "../hudhudscript-bytecode" }
hudhudscript-errors = { path = "../hudhudscript-errors" }
hudhud-http = { path = "../hudhud-http" }
