use super::{BuiltinMember, BuiltinModule, MemberKind};

pub const BUILTIN_MODULES_CORE: &[BuiltinModule] = &[
    BuiltinModule {
        name: "Math",
        description: "Mathematical functions and constants",
        members: &[
            BuiltinMember {
                name: "PI",
                kind: MemberKind::Constant,
                description: "Mathematical constant pi (3.14159...)",
                params: &[],
                return_type: "number",
            },
            BuiltinMember {
                name: "E",
                kind: MemberKind::Constant,
                description: "Euler's number (2.71828...)",
                params: &[],
                return_type: "number",
            },
            BuiltinMember {
                name: "abs",
                kind: MemberKind::Function,
                description: "Absolute value",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "sqrt",
                kind: MemberKind::Function,
                description: "Square root",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "floor",
                kind: MemberKind::Function,
                description: "Round down to nearest integer",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "ceil",
                kind: MemberKind::Function,
                description: "Round up to nearest integer",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "round",
                kind: MemberKind::Function,
                description: "Round to nearest integer",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "pow",
                kind: MemberKind::Function,
                description: "Power function",
                params: &[("base", "number"), ("exp", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "min",
                kind: MemberKind::Function,
                description: "Minimum of two values",
                params: &[("a", "number"), ("b", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "max",
                kind: MemberKind::Function,
                description: "Maximum of two values",
                params: &[("a", "number"), ("b", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "sin",
                kind: MemberKind::Function,
                description: "Sine",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "cos",
                kind: MemberKind::Function,
                description: "Cosine",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "tan",
                kind: MemberKind::Function,
                description: "Tangent",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "asin",
                kind: MemberKind::Function,
                description: "Arc sine",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "acos",
                kind: MemberKind::Function,
                description: "Arc cosine",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "atan",
                kind: MemberKind::Function,
                description: "Arc tangent",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "atan2",
                kind: MemberKind::Function,
                description: "Two-argument arc tangent",
                params: &[("y", "number"), ("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "log",
                kind: MemberKind::Function,
                description: "Natural logarithm",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "log10",
                kind: MemberKind::Function,
                description: "Base-10 logarithm",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "log2",
                kind: MemberKind::Function,
                description: "Base-2 logarithm",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "exp",
                kind: MemberKind::Function,
                description: "Exponential (e^x)",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "sign",
                kind: MemberKind::Function,
                description: "Sign of number (-1, 0, 1)",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "trunc",
                kind: MemberKind::Function,
                description: "Truncate to integer",
                params: &[("x", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "hypot",
                kind: MemberKind::Function,
                description: "Hypotenuse",
                params: &[("x", "number"), ("y", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "clamp",
                kind: MemberKind::Function,
                description: "Clamp value to range",
                params: &[("val", "number"), ("min", "number"), ("max", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "random",
                kind: MemberKind::Function,
                description: "Random number 0..1",
                params: &[],
                return_type: "number",
            },
        ],
    },
    BuiltinModule {
        name: "JSON",
        description: "JSON parse and stringify",
        members: &[
            BuiltinMember {
                name: "parse",
                kind: MemberKind::Function,
                description: "Parse JSON string to value",
                params: &[("text", "string")],
                return_type: "any",
            },
            BuiltinMember {
                name: "stringify",
                kind: MemberKind::Function,
                description: "Convert value to JSON string",
                params: &[("value", "any")],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "TOML",
        description: "TOML parse and stringify",
        members: &[
            BuiltinMember {
                name: "parse",
                kind: MemberKind::Function,
                description: "Parse TOML string",
                params: &[("text", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "stringify",
                kind: MemberKind::Function,
                description: "Convert to TOML string",
                params: &[("value", "object")],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "YAML",
        description: "YAML parse and stringify",
        members: &[
            BuiltinMember {
                name: "parse",
                kind: MemberKind::Function,
                description: "Parse YAML string",
                params: &[("text", "string")],
                return_type: "any",
            },
            BuiltinMember {
                name: "stringify",
                kind: MemberKind::Function,
                description: "Convert to YAML string",
                params: &[("value", "any")],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "CSV",
        description: "CSV parse and stringify",
        members: &[
            BuiltinMember {
                name: "parse",
                kind: MemberKind::Function,
                description: "Parse CSV string to array of objects",
                params: &[("text", "string")],
                return_type: "array",
            },
            BuiltinMember {
                name: "stringify",
                kind: MemberKind::Function,
                description: "Convert array of objects to CSV",
                params: &[("rows", "array")],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "Base64",
        description: "Base64 encoding and decoding",
        members: &[
            BuiltinMember {
                name: "encode",
                kind: MemberKind::Function,
                description: "Encode string to Base64",
                params: &[("data", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "decode",
                kind: MemberKind::Function,
                description: "Decode Base64 to string",
                params: &[("encoded", "string")],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "Hex",
        description: "Hexadecimal encoding and decoding",
        members: &[
            BuiltinMember {
                name: "encode",
                kind: MemberKind::Function,
                description: "Encode string to hex",
                params: &[("data", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "decode",
                kind: MemberKind::Function,
                description: "Decode hex to string",
                params: &[("encoded", "string")],
                return_type: "string",
            },
        ],
    },
];
