use super::{BuiltinMember, BuiltinModule, MemberKind};

pub const BUILTIN_MODULES_IO: &[BuiltinModule] = &[
    BuiltinModule {
        name: "URL",
        description: "URL encoding and decoding",
        members: &[
            BuiltinMember {
                name: "encode",
                kind: MemberKind::Function,
                description: "Percent-encode a URL component",
                params: &[("text", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "decode",
                kind: MemberKind::Function,
                description: "Decode a percent-encoded URL component",
                params: &[("text", "string")],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "Path",
        description: "File path manipulation",
        members: &[
            BuiltinMember {
                name: "join",
                kind: MemberKind::Function,
                description: "Join path segments",
                params: &[("parts", "...string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "parent",
                kind: MemberKind::Function,
                description: "Get parent directory",
                params: &[("path", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "filename",
                kind: MemberKind::Function,
                description: "Get file name from path",
                params: &[("path", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "extension",
                kind: MemberKind::Function,
                description: "Get file extension",
                params: &[("path", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "resolve",
                kind: MemberKind::Function,
                description: "Resolve to absolute path",
                params: &[("path", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "isAbsolute",
                kind: MemberKind::Function,
                description: "Check if path is absolute",
                params: &[("path", "string")],
                return_type: "boolean",
            },
        ],
    },
    BuiltinModule {
        name: "Date",
        description: "Date and time operations",
        members: &[
            BuiltinMember {
                name: "now",
                kind: MemberKind::Function,
                description: "Current timestamp in milliseconds",
                params: &[],
                return_type: "number",
            },
            BuiltinMember {
                name: "parse",
                kind: MemberKind::Function,
                description: "Parse date string to timestamp",
                params: &[("text", "string")],
                return_type: "number",
            },
            BuiltinMember {
                name: "format",
                kind: MemberKind::Function,
                description: "Format timestamp to string",
                params: &[("timestamp", "number"), ("fmt", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "from_timestamp",
                kind: MemberKind::Function,
                description: "Create date object from timestamp",
                params: &[("timestamp", "number")],
                return_type: "object",
            },
            BuiltinMember {
                name: "parts",
                kind: MemberKind::Function,
                description: "Get date components (year, month, day, etc.)",
                params: &[("timestamp", "number")],
                return_type: "object",
            },
            BuiltinMember {
                name: "diff",
                kind: MemberKind::Function,
                description: "Difference between two timestamps",
                params: &[("a", "number"), ("b", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "add",
                kind: MemberKind::Function,
                description: "Add duration to timestamp",
                params: &[("timestamp", "number"), ("ms", "number")],
                return_type: "number",
            },
            BuiltinMember {
                name: "iso",
                kind: MemberKind::Function,
                description: "Format timestamp as ISO 8601 string",
                params: &[("timestamp", "number")],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "Regex",
        description: "Regular expression operations",
        members: &[
            BuiltinMember {
                name: "test",
                kind: MemberKind::Function,
                description: "Test if pattern matches string",
                params: &[("pattern", "string"), ("text", "string")],
                return_type: "boolean",
            },
            BuiltinMember {
                name: "match",
                kind: MemberKind::Function,
                description: "First match with capture groups",
                params: &[("pattern", "string"), ("text", "string")],
                return_type: "any",
            },
            BuiltinMember {
                name: "find_all",
                kind: MemberKind::Function,
                description: "Find all matches in string",
                params: &[("pattern", "string"), ("text", "string")],
                return_type: "array",
            },
            BuiltinMember {
                name: "replace",
                kind: MemberKind::Function,
                description: "Replace first match",
                params: &[
                    ("pattern", "string"),
                    ("text", "string"),
                    ("replacement", "string"),
                ],
                return_type: "string",
            },
            BuiltinMember {
                name: "replace_all",
                kind: MemberKind::Function,
                description: "Replace all matches",
                params: &[
                    ("pattern", "string"),
                    ("text", "string"),
                    ("replacement", "string"),
                ],
                return_type: "string",
            },
            BuiltinMember {
                name: "split",
                kind: MemberKind::Function,
                description: "Split string by regex pattern",
                params: &[("pattern", "string"), ("text", "string")],
                return_type: "array",
            },
            BuiltinMember {
                name: "escape",
                kind: MemberKind::Function,
                description: "Escape special regex characters",
                params: &[("text", "string")],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "http",
        description: "HTTP client operations",
        members: &[
            BuiltinMember {
                name: "get",
                kind: MemberKind::Function,
                description: "Send HTTP GET request",
                params: &[("url", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "post",
                kind: MemberKind::Function,
                description: "Send HTTP POST request",
                params: &[("url", "string"), ("body", "any")],
                return_type: "object",
            },
            BuiltinMember {
                name: "put",
                kind: MemberKind::Function,
                description: "Send HTTP PUT request",
                params: &[("url", "string"), ("body", "any")],
                return_type: "object",
            },
            BuiltinMember {
                name: "delete",
                kind: MemberKind::Function,
                description: "Send HTTP DELETE request",
                params: &[("url", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "patch",
                kind: MemberKind::Function,
                description: "Send HTTP PATCH request",
                params: &[("url", "string"), ("body", "any")],
                return_type: "object",
            },
        ],
    },
    BuiltinModule {
        name: "file",
        description: "File I/O operations",
        members: &[
            BuiltinMember {
                name: "read",
                kind: MemberKind::Function,
                description: "Read file contents as string",
                params: &[("path", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "write",
                kind: MemberKind::Function,
                description: "Write string to file",
                params: &[("path", "string"), ("content", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "append",
                kind: MemberKind::Function,
                description: "Append string to file",
                params: &[("path", "string"), ("content", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "delete",
                kind: MemberKind::Function,
                description: "Delete a file",
                params: &[("path", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "exists",
                kind: MemberKind::Function,
                description: "Check if file exists",
                params: &[("path", "string")],
                return_type: "boolean",
            },
            BuiltinMember {
                name: "list",
                kind: MemberKind::Function,
                description: "List directory contents",
                params: &[("path", "string")],
                return_type: "array",
            },
        ],
    },
    BuiltinModule {
        name: "fs",
        description: "Filesystem operations",
        members: &[
            BuiltinMember {
                name: "chmod",
                kind: MemberKind::Function,
                description: "Change file permissions",
                params: &[("path", "string"), ("mode", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "chown",
                kind: MemberKind::Function,
                description: "Change file owner",
                params: &[("path", "string"), ("owner", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "symlink",
                kind: MemberKind::Function,
                description: "Create symbolic link",
                params: &[("target", "string"), ("link", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "readlink",
                kind: MemberKind::Function,
                description: "Read symbolic link target",
                params: &[("path", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "stat",
                kind: MemberKind::Function,
                description: "Get file metadata",
                params: &[("path", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "mkdir_p",
                kind: MemberKind::Function,
                description: "Create directory recursively",
                params: &[("path", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "copy",
                kind: MemberKind::Function,
                description: "Copy file or directory",
                params: &[("src", "string"), ("dst", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "rename",
                kind: MemberKind::Function,
                description: "Rename/move file or directory",
                params: &[("src", "string"), ("dst", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "realpath",
                kind: MemberKind::Function,
                description: "Resolve symlinks and return canonical path",
                params: &[("path", "string")],
                return_type: "string",
            },
        ],
    },
];
