use super::{BuiltinMember, BuiltinModule, MemberKind};

pub const BUILTIN_MODULES_SYSTEM: &[BuiltinModule] = &[
    BuiltinModule {
        name: "exec",
        description: "Process execution",
        members: &[
            BuiltinMember {
                name: "run",
                kind: MemberKind::Function,
                description: "Run command and wait for completion",
                params: &[("cmd", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "output",
                kind: MemberKind::Function,
                description: "Run command and capture output",
                params: &[("cmd", "string")],
                return_type: "string",
            },
            BuiltinMember {
                name: "stream",
                kind: MemberKind::Function,
                description: "Run command with streaming output",
                params: &[("cmd", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "kill",
                kind: MemberKind::Function,
                description: "Kill a running process",
                params: &[("pid", "number")],
                return_type: "null",
            },
            BuiltinMember {
                name: "spawn",
                kind: MemberKind::Function,
                description: "Spawn a background process",
                params: &[("cmd", "string")],
                return_type: "object",
            },
        ],
    },
    BuiltinModule {
        name: "tcp",
        description: "TCP networking",
        members: &[
            BuiltinMember {
                name: "connect",
                kind: MemberKind::Function,
                description: "Connect to TCP server",
                params: &[("host", "string"), ("port", "number")],
                return_type: "object",
            },
            BuiltinMember {
                name: "listen",
                kind: MemberKind::Function,
                description: "Listen on TCP port",
                params: &[("port", "number")],
                return_type: "object",
            },
            BuiltinMember {
                name: "accept",
                kind: MemberKind::Function,
                description: "Accept incoming TCP connection",
                params: &[("listener", "object")],
                return_type: "object",
            },
            BuiltinMember {
                name: "write",
                kind: MemberKind::Function,
                description: "Write data to TCP connection",
                params: &[("conn", "object"), ("data", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "read",
                kind: MemberKind::Function,
                description: "Read data from TCP connection",
                params: &[("conn", "object")],
                return_type: "string",
            },
            BuiltinMember {
                name: "close",
                kind: MemberKind::Function,
                description: "Close TCP connection",
                params: &[("conn", "object")],
                return_type: "null",
            },
        ],
    },
    BuiltinModule {
        name: "udp",
        description: "UDP networking",
        members: &[
            BuiltinMember {
                name: "bind",
                kind: MemberKind::Function,
                description: "Bind UDP socket to port",
                params: &[("port", "number")],
                return_type: "object",
            },
            BuiltinMember {
                name: "send",
                kind: MemberKind::Function,
                description: "Send UDP datagram",
                params: &[("socket", "object"), ("data", "string"), ("addr", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "recv",
                kind: MemberKind::Function,
                description: "Receive UDP datagram",
                params: &[("socket", "object")],
                return_type: "object",
            },
            BuiltinMember {
                name: "close",
                kind: MemberKind::Function,
                description: "Close UDP socket",
                params: &[("socket", "object")],
                return_type: "null",
            },
        ],
    },
    BuiltinModule {
        name: "ws",
        description: "WebSocket client",
        members: &[
            BuiltinMember {
                name: "connect",
                kind: MemberKind::Function,
                description: "Connect to WebSocket server",
                params: &[("url", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "send",
                kind: MemberKind::Function,
                description: "Send WebSocket message",
                params: &[("conn", "object"), ("data", "string")],
                return_type: "null",
            },
            BuiltinMember {
                name: "recv",
                kind: MemberKind::Function,
                description: "Receive WebSocket message",
                params: &[("conn", "object")],
                return_type: "string",
            },
            BuiltinMember {
                name: "close",
                kind: MemberKind::Function,
                description: "Close WebSocket connection",
                params: &[("conn", "object")],
                return_type: "null",
            },
        ],
    },
    BuiltinModule {
        name: "uuid",
        description: "UUID generation and parsing",
        members: &[
            BuiltinMember {
                name: "v4",
                kind: MemberKind::Function,
                description: "Generate random UUID v4",
                params: &[],
                return_type: "string",
            },
            BuiltinMember {
                name: "v7",
                kind: MemberKind::Function,
                description: "Generate time-ordered UUID v7",
                params: &[],
                return_type: "string",
            },
            BuiltinMember {
                name: "parse",
                kind: MemberKind::Function,
                description: "Parse and validate UUID string",
                params: &[("text", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "nil",
                kind: MemberKind::Function,
                description: "Return nil UUID (all zeros)",
                params: &[],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "Temp",
        description: "Temporary file and directory creation",
        members: &[
            BuiltinMember {
                name: "file",
                kind: MemberKind::Function,
                description: "Create a temporary file",
                params: &[],
                return_type: "string",
            },
            BuiltinMember {
                name: "dir",
                kind: MemberKind::Function,
                description: "Create a temporary directory",
                params: &[],
                return_type: "string",
            },
            BuiltinMember {
                name: "path",
                kind: MemberKind::Function,
                description: "Generate a temporary path without creating it",
                params: &[],
                return_type: "string",
            },
        ],
    },
    BuiltinModule {
        name: "Glob",
        description: "Glob pattern matching",
        members: &[
            BuiltinMember {
                name: "find",
                kind: MemberKind::Function,
                description: "Find files matching glob pattern",
                params: &[("pattern", "string")],
                return_type: "array",
            },
            BuiltinMember {
                name: "match",
                kind: MemberKind::Function,
                description: "Test if path matches glob pattern",
                params: &[("pattern", "string"), ("path", "string")],
                return_type: "boolean",
            },
        ],
    },
    BuiltinModule {
        name: "INI",
        description: "INI file parse and stringify",
        members: &[
            BuiltinMember {
                name: "parse",
                kind: MemberKind::Function,
                description: "Parse INI string to object",
                params: &[("text", "string")],
                return_type: "object",
            },
            BuiltinMember {
                name: "stringify",
                kind: MemberKind::Function,
                description: "Convert object to INI string",
                params: &[("value", "object")],
                return_type: "string",
            },
        ],
    },
];
