use crate::header_parser::{CppClass, CppEnum, CppFunction, CppHeader};

/// Generate HudHudScript (.hud) content from a parsed C++ header.
pub fn generate_hud(header: &CppHeader, lib_name: &str) -> String {
    let mut output = String::new();

    // File header comment
    output.push_str("// Auto-generated by hudconv\n");
    output.push_str(&format!("// Source library: {}\n\n", lib_name));

    // Generate enums
    for e in &header.enums {
        output.push_str(&generate_enum(e));
        output.push('\n');
    }

    // Generate subjects (from classes) and agents (from structs)
    for cls in &header.classes {
        if cls.is_struct {
            output.push_str(&generate_agent(cls));
        } else {
            output.push_str(&generate_subject(cls, lib_name));
        }
        output.push('\n');
    }

    // Generate tools (from free functions)
    for func in &header.functions {
        output.push_str(&generate_tool(func));
        output.push('\n');
    }

    output
}

pub fn generate_enum(e: &CppEnum) -> String {
    let mut out = String::new();
    out.push_str(&format!("enum {} {{\n", e.name));
    for (i, variant) in e.variants.iter().enumerate() {
        out.push_str(&format!("    {}", variant));
        if i < e.variants.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

pub fn generate_subject(cls: &CppClass, lib_name: &str) -> String {
    let mut out = String::new();

    let native_attr = format!("@custom(native: \"{}\")\n", lib_name);
    out.push_str(&native_attr);

    if let Some(parent) = &cls.parent {
        out.push_str(&format!("subject {} extends {} {{\n", cls.name, parent));
    } else {
        out.push_str(&format!("subject {} {{\n", cls.name));
    }

    // Fields -> state
    for field in &cls.fields {
        let hud_type = cpp_type_to_hud(&field.field_type);
        let default = default_value_for_type(&hud_type);
        out.push_str(&format!(
            "    state {}: {}\n",
            strip_member_prefix(&field.name),
            default
        ));
    }

    if !cls.fields.is_empty() && !cls.methods.is_empty() {
        out.push('\n');
    }

    // Methods -> capabilities
    for method in &cls.methods {
        if method.is_static {
            // Static methods become tools
            out.push_str(&format!("    tool {} {{\n", to_snake_case(&method.name)));
            for (ty, name) in &method.params {
                if !name.is_empty() {
                    out.push_str(&format!(
                        "        input {}: {}\n",
                        name,
                        cpp_type_to_hud(ty)
                    ));
                }
            }
            out.push_str("    }\n");
        } else {
            out.push_str(&format!("    can {}", to_snake_case(&method.name)));
            if !method.params.is_empty() {
                let params: Vec<String> = method
                    .params
                    .iter()
                    .filter(|(_, n)| !n.is_empty())
                    .map(|(ty, name)| format!("{}: {}", name, cpp_type_to_hud(ty)))
                    .collect();
                if !params.is_empty() {
                    out.push_str(&format!("({})", params.join(", ")));
                }
            }
            out.push('\n');
        }
    }

    out.push_str("}\n");
    out
}

pub fn generate_agent(cls: &CppClass) -> String {
    let mut out = String::new();

    out.push_str(&format!("agent {} {{\n", cls.name));

    for field in &cls.fields {
        let hud_type = cpp_type_to_hud(&field.field_type);
        let default = default_value_for_type(&hud_type);
        out.push_str(&format!(
            "    state {}: {}\n",
            strip_member_prefix(&field.name),
            default
        ));
    }

    out.push_str("}\n");
    out
}

pub fn generate_tool(func: &CppFunction) -> String {
    let mut out = String::new();

    out.push_str(&format!("tool {} {{\n", to_snake_case(&func.name)));

    for (ty, name) in &func.params {
        if !name.is_empty() {
            out.push_str(&format!("    input {}: {}\n", name, cpp_type_to_hud(ty)));
        }
    }

    let return_hud = cpp_type_to_hud(&func.return_type);
    if return_hud != "void" {
        out.push_str(&format!("    output result: {}\n", return_hud));
    }

    out.push_str("}\n");
    out
}

/// Convert a C++ type name to a HudHudScript type.
pub fn cpp_type_to_hud(cpp_type: &str) -> String {
    let t = cpp_type
        .trim()
        .replace("const ", "")
        .replace("&", "")
        .replace("*", "")
        .trim()
        .to_string();

    match t.as_str() {
        "int" | "long" | "short" | "int32_t" | "int64_t" | "size_t" | "unsigned" => {
            "number".to_string()
        }
        "float" | "double" => "number".to_string(),
        "bool" => "boolean".to_string(),
        "std::string" | "string" | "char" => "text".to_string(),
        "void" => "void".to_string(),
        other => other.to_string(),
    }
}

/// Get a default value for a HudHudScript type.
pub fn default_value_for_type(hud_type: &str) -> String {
    match hud_type {
        "number" => "0".to_string(),
        "boolean" => "false".to_string(),
        "text" => "\"\"".to_string(),
        _ => "null".to_string(),
    }
}

/// Strip common C++ member prefixes (m_, _).
pub fn strip_member_prefix(name: &str) -> &str {
    if let Some(stripped) = name.strip_prefix("m_") {
        stripped
    } else if name.starts_with('_') && name.len() > 1 {
        &name[1..]
    } else {
        name
    }
}

/// Convert camelCase or PascalCase to snake_case.
pub fn to_snake_case(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        } else {
            result.push(ch);
        }
    }
    result
}
