use crate::cmake_parser::CMakeProject;
use crate::conan_parser::ConanProject;

/// Generate hudhud.toml manifest content from CMake and/or Conan project metadata.
pub fn generate_manifest(cmake: Option<&CMakeProject>, conan: Option<&ConanProject>) -> String {
    let mut output = String::new();

    output.push_str("# Auto-generated by hudconv\n\n");

    // [package] section
    output.push_str("[package]\n");

    let name = cmake
        .map(|c| c.name.clone())
        .or_else(|| conan.map(|c| c.name.clone()))
        .unwrap_or_else(|| "converted-package".to_string());

    let version = cmake
        .and_then(|c| c.version.clone())
        .or_else(|| conan.map(|c| c.version.clone()))
        .unwrap_or_else(|| "0.1.0".to_string());

    let pkg_type = if let Some(cmake) = cmake {
        if !cmake.libraries.is_empty() && cmake.executables.is_empty() {
            "library"
        } else if cmake.libraries.is_empty() && !cmake.executables.is_empty() {
            "executable"
        } else {
            "mixed"
        }
    } else {
        "library"
    };

    output.push_str(&format!("name = \"{}\"\n", to_kebab_case(&name)));
    output.push_str(&format!("version = \"{}\"\n", version));
    output.push_str(&format!("type = \"{}\"\n", pkg_type));
    output.push_str("description = \"Converted from C++ project\"\n");

    // [native-dependencies] section
    let mut deps = Vec::new();

    if let Some(cmake) = cmake {
        // Add a self-reference for the original library
        if !cmake.libraries.is_empty() {
            deps.push(format!(
                "{} = {{ path = \"./\", type = \"cmake\" }}",
                to_kebab_case(&cmake.libraries[0].name)
            ));
        }
    }

    if let Some(conan) = conan {
        for req in &conan.requires {
            // Parse "pkg/version" format
            let parts: Vec<&str> = req.splitn(2, '/').collect();
            if parts.len() == 2 {
                deps.push(format!(
                    "{} = {{ conan = \"{}\" }}",
                    to_kebab_case(parts[0]),
                    req
                ));
            }
        }
    }

    if !deps.is_empty() {
        output.push_str("\n[native-dependencies]\n");
        for dep in &deps {
            output.push_str(dep);
            output.push('\n');
        }
    }

    // [build] section
    output.push_str("\n[build]\n");
    output.push_str("script = \"build.sh\"\n");

    output
}

/// Generate a build.sh script for the project.
pub fn generate_build_script(cmake: Option<&CMakeProject>, conan: Option<&ConanProject>) -> String {
    let mut output = String::new();

    output.push_str("#!/bin/bash\n");
    output.push_str("# Auto-generated by hudconv\n");
    output.push_str("set -euo pipefail\n\n");

    if conan.is_some() {
        output.push_str("# Install Conan dependencies\n");
        output.push_str("conan install . --output-folder=build --build=missing\n\n");
    }

    if cmake.is_some() {
        output.push_str("# Configure with CMake\n");
        if conan.is_some() {
            output
                .push_str("cmake -B build -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake\n\n");
        } else {
            output.push_str("cmake -B build\n\n");
        }
        output.push_str("# Build\n");
        output.push_str("cmake --build build\n");
    }

    output
}

/// Convert a name to kebab-case.
pub fn to_kebab_case(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                result.push('-');
            }
            result.push(ch.to_lowercase().next().unwrap());
        } else if ch == '_' {
            result.push('-');
        } else {
            result.push(ch);
        }
    }
    result
}
