[package]
name = "hudhudscript-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
hudhudscript-mir = { path = "../hudhudscript-mir" }
hudhudscript-target = { path = "../hudhudscript-target" }
