pub(crate) static PT_KEYWORDS: &[(&'static str, &'static str)] = &[
    ("acorde", "chord"),
    ("aguardar", "await"),
    ("aplicação", "enforcement"),
    ("armazém", "store"),
    ("assíncrono", "async"),
    ("através", "via"),
    ("ação", "action"),
    ("configuração", "config"),
    ("constituição", "constitution"),
    ("estilo_comunicação", "communication_style"),
    ("fiscalização", "enforcement"),
    ("função", "function"),
    ("intenção", "intent"),
    ("padrão", "default"),
    ("percepção", "perception"),
    ("relação", "relation"),
    ("senão", "else"),
];
