use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;

use crate::{Resolved, LOCKFILE};

/// Lockfile persisted as `hudhud.lock`.
#[derive(Serialize, Deserialize, Default)]
pub(crate) struct Lockfile {
    #[serde(default)]
    pub(crate) metadata: LockfileMetadata,
    #[serde(default, rename = "package")]
    pub(crate) packages: BTreeMap<String, LockedPackage>,
}

#[derive(Serialize, Deserialize, Default)]
pub(crate) struct LockfileMetadata {
    #[serde(default)]
    pub(crate) version: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct LockedPackage {
    pub(crate) version: String,
    pub(crate) source: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) dependencies: Vec<String>,
}

pub(crate) fn write_lockfile(resolved: &BTreeMap<String, Resolved>) {
    let lockfile = Lockfile {
        metadata: LockfileMetadata { version: 1 },
        packages: resolved
            .iter()
            .map(|(name, r)| {
                (
                    name.clone(),
                    LockedPackage {
                        version: r.version.clone(),
                        source: format!("local:{}", r.source_path.display()),
                        dependencies: r.dependencies.clone(),
                    },
                )
            })
            .collect(),
    };

    let content = toml::to_string_pretty(&lockfile).expect("Failed to serialize lockfile");
    let output = format!(
        "# This file is auto-generated by hudpkg. Do not edit manually.\n\n{}",
        content
    );

    if let Err(e) = fs::write(LOCKFILE, output) {
        eprintln!("Warning: could not write {}: {}", LOCKFILE, e);
    } else {
        println!("  Updated {}", LOCKFILE);
    }
}

pub(crate) fn load_lockfile() -> Result<Lockfile, String> {
    let content =
        fs::read_to_string(LOCKFILE).map_err(|e| format!("Failed to read {}: {}", LOCKFILE, e))?;
    toml::from_str(&content).map_err(|e| format!("Failed to parse {}: {}", LOCKFILE, e))
}
