[package]
name = "hudhudscript-native-abi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
libc = "0.2"
num-bigint = "0.4"
num-traits = "0.2"

[lib]
crate-type = ["rlib", "staticlib"]
