use crate::catalog::category::ExceptionCategory;
use crate::catalog::codes::ExceptionCode;
use crate::catalog::entry::ExceptionEntry;

mod event;
pub use event::*;
mod layer;
pub use layer::*;
mod network;
pub use network::*;
mod orchestration;
pub use orchestration::*;
mod permission;
pub use permission::*;

pub static TABLE: &[ExceptionEntry] = &[
    EVENT_BUS_CHANNEL_CLOSED,
    EVENT_BUS_NO_SUBSCRIBERS,
    LAYER_DEPENDENCY_NOT_FOUND,
    LAYER_EXECUTION_FAILED,
    LAYER_LAYER_ALREADY_EXISTS,
    LAYER_LAYER_NOT_FOUND,
    LAYER_TIMEOUT_EXCEEDED,
    NETWORK_CYCLIC_DEPENDENCY,
    NETWORK_INVALID_TOPOLOGY,
    NETWORK_LAYER_EXECUTION_FAILED,
    NETWORK_LAYER_NOT_FOUND,
    NETWORK_NETWORK_ALREADY_EXISTS,
    NETWORK_NETWORK_NOT_FOUND,
    NETWORK_TIMEOUT_EXCEEDED,
    ORCHESTRATION_INVALID_WORKFLOW,
    ORCHESTRATION_LAYER_ERROR,
    ORCHESTRATION_NETWORK_ERROR,
    ORCHESTRATION_NETWORK_EXECUTION_FAILED,
    ORCHESTRATION_NETWORK_NOT_FOUND,
    ORCHESTRATION_WORKFLOW_ALREADY_EXISTS,
    ORCHESTRATION_WORKFLOW_NOT_FOUND,
    ORCHESTRATION_WORKFLOW_TIMED_OUT,
    PERMISSION_AGENT_NOT_REGISTERED,
    PERMISSION_DENIED,
];
