//! Native ABI symbol registrations for Cranelift JITBuilder.

use cranelift_jit::JITBuilder;

/// Registers all native runtime symbols into JITBuilder.
pub fn register_symbols(builder: &mut JITBuilder) {
    let symbols: &[(&str, *const u8)] = &[
        ("hudhud_print_int", hudhudscript_native_abi::hudhud_print_int as *const u8),
        ("hudhud_print_float", hudhudscript_native_abi::hudhud_print_float as *const u8),
        ("hudhud_print_str", hudhudscript_native_abi::hudhud_print_str as *const u8),
        ("fmod", libm::fmod as *const u8),
        ("hudhud_date_millis", hudhudscript_native_abi::hudhud_date_millis as *const u8),
        ("hudhud_math_sin", hudhudscript_native_abi::hudhud_math_sin as *const u8),
        ("hudhud_math_sqrt", hudhudscript_native_abi::hudhud_math_sqrt as *const u8),
        ("hudhud_math_cos", hudhudscript_native_abi::hudhud_math_cos as *const u8),
        ("hudhud_math_floor", hudhudscript_native_abi::hudhud_math_floor as *const u8),
        ("hudhud_math_abs", hudhudscript_native_abi::hudhud_math_abs as *const u8),
        ("hudhud_math_pow", hudhudscript_native_abi::hudhud_math_pow as *const u8),
        ("hudhud_math_min", hudhudscript_native_abi::hudhud_math_min as *const u8),
        ("hudhud_math_max", hudhudscript_native_abi::hudhud_math_max as *const u8),
        ("hudhud_assert_eq", hudhudscript_native_abi::hudhud_assert_eq as *const u8),
        ("hudhud_assert_approx", hudhudscript_native_abi::hudhud_assert_approx as *const u8),
        ("hudhud_assert_true", hudhudscript_native_abi::hudhud_assert_true as *const u8),
        ("hudhud_assert_false", hudhudscript_native_abi::hudhud_assert_false as *const u8),
        ("hudhud_dyn_call_method", hudhudscript_native_abi::hudhud_dyn_call_method as *const u8),
        ("hudhud_input", hudhudscript_native_abi::hudhud_input as *const u8),
        ("hudhud_confirm", hudhudscript_native_abi::hudhud_confirm as *const u8),
        ("hudhud_globals", hudhudscript_native_abi::hudhud_globals as *const u8),
        ("hudhud_global_get", hudhudscript_native_abi::hudhud_global_get as *const u8),
        ("hudhud_global_set", hudhudscript_native_abi::hudhud_global_set as *const u8),
        ("hudhud_string_concat", hudhudscript_native_abi::hudhud_string_concat as *const u8),
        ("hudhud_string_len", hudhudscript_native_abi::hudhud_string_len as *const u8),
        ("hudhud_string_eq", hudhudscript_native_abi::hudhud_string_eq as *const u8),
        ("hudhud_int_to_string", hudhudscript_native_abi::hudhud_int_to_string as *const u8),
        ("hudhud_float_to_string", hudhudscript_native_abi::hudhud_float_to_string as *const u8),
        ("hudhud_string_char_at", hudhudscript_native_abi::hudhud_string_char_at as *const u8),
        ("hudhud_ascii_chars", hudhudscript_native_abi::hudhud_ascii_chars.as_ptr() as *const u8),
        ("hudhud_string_substring", hudhudscript_native_abi::hudhud_string_substring as *const u8),
        ("hudhud_string_to_int", hudhudscript_native_abi::hudhud_string_to_int as *const u8),
        ("hudhud_string_split", hudhudscript_native_abi::hudhud_string_split as *const u8),
        ("hudhud_string_index_of", hudhudscript_native_abi::hudhud_string_index_of as *const u8),
        ("hudhud_array_new", hudhudscript_native_abi::hudhud_array_new as *const u8),
        ("hudhud_array_filled", hudhudscript_native_abi::hudhud_array_filled as *const u8),
        ("hudhud_array_fill", hudhudscript_native_abi::hudhud_array_fill as *const u8),
        ("hudhud_array_push", hudhudscript_native_abi::hudhud_array_push as *const u8),
        ("hudhud_array_get", hudhudscript_native_abi::hudhud_array_get as *const u8),
        ("hudhud_array_set", hudhudscript_native_abi::hudhud_array_set as *const u8),
        ("hudhud_array_len", hudhudscript_native_abi::hudhud_array_len as *const u8),
        ("hudhud_array_pop", hudhudscript_native_abi::hudhud_array_pop as *const u8),
        ("hudhud_array_join", hudhudscript_native_abi::hudhud_array_join as *const u8),
        ("hudhud_object_new", hudhudscript_native_abi::hudhud_object_new as *const u8),
        ("hudhud_object_set", hudhudscript_native_abi::hudhud_object_set as *const u8),
        ("hudhud_object_get", hudhudscript_native_abi::hudhud_object_get as *const u8),
        ("hudhud_object_has", hudhudscript_native_abi::hudhud_object_has as *const u8),
        ("hudhud_object_len", hudhudscript_native_abi::hudhud_object_len as *const u8),
        ("hudhud_typeof", hudhudscript_native_abi::hudhud_typeof as *const u8),
        ("hudhud_register_string", hudhudscript_native_abi::hudhud_register_string as *const u8),
        ("hudhud_bigint_add_trusted", hudhudscript_native_abi::hudhud_bigint_add_trusted as *const u8),
        ("hudhud_bigint_sub_trusted", hudhudscript_native_abi::hudhud_bigint_sub_trusted as *const u8),
        ("hudhud_bigint_mul_trusted", hudhudscript_native_abi::hudhud_bigint_mul_trusted as *const u8),
        ("hudhud_string_cmp", hudhudscript_native_abi::hudhud_string_cmp as *const u8),
        ("hudhud_string_append", hudhudscript_native_abi::hudhud_string_append as *const u8),
        ("hudhud_throw", hudhudscript_native_abi::hudhud_throw as *const u8),
        ("hudhud_has_exception", hudhudscript_native_abi::hudhud_has_exception as *const u8),
        ("hudhud_catch", hudhudscript_native_abi::hudhud_catch as *const u8),
        ("hudhud_num_add", hudhudscript_native_abi::hudhud_num_add as *const u8),
        ("hudhud_num_sub", hudhudscript_native_abi::hudhud_num_sub as *const u8),
        ("hudhud_num_mul", hudhudscript_native_abi::hudhud_num_mul as *const u8),
        ("hudhud_num_div", hudhudscript_native_abi::hudhud_num_div as *const u8),
        ("hudhud_num_rem", hudhudscript_native_abi::hudhud_num_rem as *const u8),
        ("hudhud_num_cmp", hudhudscript_native_abi::hudhud_num_cmp as *const u8),
        ("hudhud_string_trim", hudhudscript_native_abi::hudhud_string_trim as *const u8),
        ("hudhud_string_starts_with", hudhudscript_native_abi::hudhud_string_starts_with as *const u8),
        ("hudhud_string_ends_with", hudhudscript_native_abi::hudhud_string_ends_with as *const u8),
        ("hudhud_string_contains", hudhudscript_native_abi::hudhud_string_contains as *const u8),
        ("hudhud_string_replace", hudhudscript_native_abi::hudhud_string_replace as *const u8),
        ("hudhud_string_to_lower", hudhudscript_native_abi::hudhud_string_to_lower as *const u8),
        ("hudhud_string_to_upper", hudhudscript_native_abi::hudhud_string_to_upper as *const u8),
        ("hudhud_string_char_code_at", hudhudscript_native_abi::hudhud_string_char_code_at as *const u8),
        ("hudhud_array_slice", hudhudscript_native_abi::hudhud_array_slice as *const u8),
        ("hudhud_array_reverse", hudhudscript_native_abi::hudhud_array_reverse as *const u8),
        ("hudhud_array_concat", hudhudscript_native_abi::hudhud_array_concat as *const u8),
        ("hudhud_array_index_of", hudhudscript_native_abi::hudhud_array_index_of as *const u8),
        ("hudhud_array_includes", hudhudscript_native_abi::hudhud_array_includes as *const u8),
        ("hudhud_array_shift", hudhudscript_native_abi::hudhud_array_shift as *const u8),
        ("hudhud_array_unshift", hudhudscript_native_abi::hudhud_array_unshift as *const u8),
        ("hudhud_array_sort", hudhudscript_native_abi::hudhud_array_sort as *const u8),
        ("hudhud_date_now", hudhudscript_native_abi::hudhud_date_now as *const u8),
        ("hudhud_time_nanos", hudhudscript_native_abi::hudhud_time_nanos as *const u8),
        ("hudhud_time_micros", hudhudscript_native_abi::hudhud_time_micros as *const u8),
        ("hudhud_sleep_millis", hudhudscript_native_abi::hudhud_sleep_millis as *const u8),
        ("hudhud_sleep_micros", hudhudscript_native_abi::hudhud_sleep_micros as *const u8),
        ("hudhud_date_year", hudhudscript_native_abi::hudhud_date_year as *const u8),
        ("hudhud_date_month", hudhudscript_native_abi::hudhud_date_month as *const u8),
        ("hudhud_date_day", hudhudscript_native_abi::hudhud_date_day as *const u8),
        ("hudhud_date_hour", hudhudscript_native_abi::hudhud_date_hour as *const u8),
        ("hudhud_date_minute", hudhudscript_native_abi::hudhud_date_minute as *const u8),
        ("hudhud_date_second", hudhudscript_native_abi::hudhud_date_second as *const u8),
        ("hudhud_date_iso", hudhudscript_native_abi::hudhud_date_iso as *const u8),
        // data sembolü: satır-içi global erişimi (emit_global_load/store)
        ("GLOBAL_SLOTS", unsafe { hudhudscript_native_abi::object::GLOBAL_SLOTS.as_ptr() } as *const u8),
    ];
    for &(name, ptr) in symbols {
        builder.symbol(name, ptr);
    }
}
